version: '3.8'
services:
  api:
    container_name: sendgrid-integration-app
    build:
      context: .
      dockerfile: Dockerfile
      target: run
    hostname: sendgrid-integration-app
    ports:
      - "3000:3000"
    restart: on-failure