version: '3.8'
services:
  api:
    container_name: ig-bknd-counting-of-elections
    build:
      context: .
      dockerfile: Dockerfile
      target: run
    hostname: balder
    ports:
      - "3011:3011"
    restart: on-failure